study = [
    "Bachelor's Degree",
    "Master's Degree",
    "PhD",
    "B.Tech",
    "CS",
    "GRADUATION–BTECH,(CSE) Krishna INSTITUTE OF TECHNOLOG",
    "High School",
    "Associate",
    "Bachelor Engineering",
    " BACHELOR DEGREE IN ELECTRONICS ANDCOMMUNICATIONS ENGINEERING ",
    "High School Diploma",
    "Secondary School Certificate",
    "GED (General Educational Development)",
    "Senior Secondary School",
    "Honors Program",
    "Higher Secondary Certificate (HSC)",
    "Bachelor of Arts (BA)",
    "Bachelor of Science (BSc)",
    "Bachelor of Commerce (BCom)",
    "Bachelor of Engineering (BEng)",
    "Bachelor of Technology (BTech)",
    "Bachelor of Fine Arts (BFA)",
    "Bachelor of Education (BEd)",
    "Master of Arts (MA)",
    "Master of Science (MSc)",
    "Master of Business Administration (MBA)",
    "Master of Education (MEd)",
    "Master of Engineering (MEng)",
    "Master of Fine Arts (MFA)",
    "Graduate Certificate/Diploma",
]
