skill = [
    "Python",
    "JavaScript",
    "React",
    "Django",
    "SQL",
    "Machine Learning",
    "POWER BI",
    "Numpy",
    "Pandas",
    "AI",
    "python",
    "Java",
    "C++",
    "C#",
    "Ruby",
    "PHP",
    "Vue.js",
    "Node.js",
    "MongoDB",
    "PostgreSQL",
    "Oracle",
    "AWS",
    "Azure",
    "Google Cloud Platform (GCP)",
    "Cloud Security",
    "Docker",
    "Ethical Hacking",
    "Network Security",
    "Information Security",
    "Risk Assessment",
    "Git",
    "GitHub",
    "Bitbucket",
]
